// This file is auto-generated by scripts/build-experiences.js
// Do not edit manually - edit src/data/experiences.json instead

export const experiences = Object.freeze([
  {
    "id": 1,
    "company": "Tech Company Inc.",
    "position": "Senior Software Engineer",
    "startDate": "Jan 2023",
    "endDate": "Present",
    "description": "Leading the development of scalable web applications using React and Node.js. Collaborated with cross-functional teams to deliver high-quality software solutions. Mentored junior developers and conducted code reviews.",
    "location": "Remote",
    "technologies": [
      "react",
      "nodejs",
      "typescript",
      "postgresql"
    ]
  },
  {
    "id": 2,
    "company": "Digital Solutions Ltd.",
    "position": "Full Stack Developer",
    "startDate": "Jun 2021",
    "endDate": "Dec 2022",
    "description": "Developed and maintained multiple client-facing applications. Implemented RESTful APIs and integrated third-party services. Optimized application performance and improved user experience.",
    "location": "San Francisco, CA",
    "technologies": [
      "javascript",
      "nodejs",
      "mongodb",
      "react"
    ]
  },
  {
    "id": 3,
    "company": "StartUp Ventures",
    "position": "Frontend Developer",
    "startDate": "Mar 2020",
    "endDate": "May 2021",
    "description": "Built responsive and interactive user interfaces using modern JavaScript frameworks. Worked closely with designers to implement pixel-perfect designs. Participated in agile development processes.",
    "location": "New York, NY",
    "technologies": [
      "javascript",
      "vue",
      "tailwindcss"
    ]
  }
])
