// This file is auto-generated by scripts/build-experiences.js
// Do not edit manually - edit src/data/experiences.json instead

export const experiences = Object.freeze([
  {
    "id": 1,
    "company": "Load Trail Mx",
    "position": "Software developer",
    "startDate": "February 2024",
    "endDate": "June 2025",
    "description": "",
    "location": "Mexico",
    "technologies": [
      "nextjs",
      "react",
      "javascript",
      "sql"
    ]
  },
  {
    "id": 2,
    "company": "Aplicaciones NG",
    "position": "Full Stack Developer",
    "startDate": "January 2023",
    "endDate": "February 2024",
    "description": "",
    "location": "Mexico",
    "technologies": [
      "laravel",
      "vue",
      "mysql"
    ]
  }
])
