import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const aboutJsonPath = path.join(__dirname, '../src/data/about.json')
const outputPath = path.join(__dirname, '../src/constants/about.js')

try {
  // Read about.json
  const aboutData = JSON.parse(fs.readFileSync(aboutJsonPath, 'utf-8'))
  
  // Validate structure
  if (!aboutData.about || typeof aboutData.about !== 'object') {
    throw new Error('Invalid about.json structure: missing "about" object')
  }
  
  // Generate JS file content
  const fileContent = `// This file is auto-generated by scripts/build-about.js
// Do not edit manually - edit src/data/about.json instead

export const about = Object.freeze(${JSON.stringify(aboutData.about, null, 2)})
`
  
  // Ensure output directory exists
  const outputDir = path.dirname(outputPath)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }
  
  // Write to about.js
  fs.writeFileSync(outputPath, fileContent, 'utf-8')
  
  console.log('✅ About constant generated successfully')
  console.log(`   Source: src/data/about.json`)
  console.log(`   Output: src/constants/about.js`)
} catch (error) {
  console.error('❌ Error building about:', error.message)
  process.exit(1)
}
