import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const skillsJsonPath = path.join(__dirname, '../src/data/skills.json')
const outputPath = path.join(__dirname, '../src/constants/skills.js')

try {
  // Read skills.json
  const skillsData = JSON.parse(fs.readFileSync(skillsJsonPath, 'utf-8'))
  
  // Validate structure
  if (!skillsData.skills || !Array.isArray(skillsData.skills)) {
    throw new Error('Invalid skills.json structure: missing "skills" array')
  }
  
  // Generate JS file content
  const fileContent = `// This file is auto-generated by scripts/build-skills.js
// Do not edit manually - edit src/data/skills.json instead

export const skills = Object.freeze(${JSON.stringify(skillsData.skills, null, 2)})
`
  
  // Ensure output directory exists
  const outputDir = path.dirname(outputPath)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }
  
  // Write to skills.js
  fs.writeFileSync(outputPath, fileContent, 'utf-8')
  
  console.log('✅ Skills constant generated successfully')
  console.log(`   Source: src/data/skills.json`)
  console.log(`   Output: src/constants/skills.js`)
  console.log(`   Skills: ${skillsData.skills.length}`)
} catch (error) {
  console.error('❌ Error building skills:', error.message)
  process.exit(1)
}
